import { Job, District } from './types';

export const DISTRICTS: District[] = [
  {
    id: 'd1', num: 1,
    name: 'District 1 — Manila',
    cities: ['Manila'],
    color: '#C8E6C9', hoverColor: '#A5D6A7',
    jobCount: 347,
  },
  {
    id: 'd2', num: 2,
    name: 'District 2 — Inner East',
    cities: ['Mandaluyong', 'Marikina', 'Pasig', 'Quezon City', 'San Juan'],
    color: '#A5D6A7', hoverColor: '#81C784',
    jobCount: 892,
  },
  {
    id: 'd3', num: 3,
    name: 'District 3 — North',
    cities: ['Caloocan', 'Malabon', 'Navotas', 'Valenzuela'],
    color: '#81C784', hoverColor: '#66BB6A',
    jobCount: 421,
  },
  {
    id: 'd4', num: 4,
    name: 'District 4 — South',
    cities: ['Las Piñas', 'Makati', 'Muntinlupa', 'Parañaque', 'Pasay', 'Pateros', 'Taguig'],
    color: '#80CBC4', hoverColor: '#4DB6AC',
    jobCount: 1204,
  },
];

export const JOB_CATEGORIES = [
  { name: 'Food & Beverage', icon: 'UtensilsCrossed', count: 1247 },
  { name: 'Retail / Sales', icon: 'ShoppingBag', count: 892 },
  { name: 'Admin / Office', icon: 'Briefcase', count: 634 },
  { name: 'Education', icon: 'BookOpen', count: 312 },
  { name: 'Events', icon: 'CalendarDays', count: 156 },
  { name: 'Logistics', icon: 'Truck', count: 445 },
  { name: 'Healthcare', icon: 'HeartPulse', count: 289 },
  { name: 'IT / Tech', icon: 'Laptop', count: 378 },
  { name: 'Beauty / Wellness', icon: 'Sparkles', count: 223 },
  { name: 'Customer Service', icon: 'Headphones', count: 567 },
  { name: 'Manufacturing', icon: 'Factory', count: 334 },
  { name: 'Others', icon: 'MoreHorizontal', count: 892 },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'j001',
    title: '【Barista / Cashier / Floor Staff】 Coffee Shop Part-Timer — No Experience OK!',
    company: 'Brew & Bean Café — BGC Branch',
    employmentType: '[ア・パ]',
    jobType: ['Barista', 'Cashier', 'Floor Staff / Service'],
    salary: { type: 'Hourly', min: 80, max: 110, note: '+ Transportation allowance up to ₱150/day' },
    schedule: ['Weekdays OK', '2–3×/week OK', '4-hour shifts OK', '~6 hrs/day', 'Mornings', 'Afternoons'],
    scheduleNote: '[ア・パ] 07:00–22:00 (shift consultation)',
    location: 'BGC, Taguig City (near Market! Market!)',
    nearestStation: ['Ayala MRT-3 (15 min commute)', 'BGC Bus — East Express (direct)'],
    features: ['No Experience OK', 'Students OK', 'Uniform Provided', 'Immediate Start', 'Transportation Allowance', 'Meal Allowance', 'Weekly Pay OK'],
    ageGroupSlider: 2,
    genderRatioSlider: 3,
    workStyleSlider: 3,
    workplaceVibeSlider: 4,
    workTypeSlider: 4,
    customerInteractionSlider: 5,
    externalInteractionSlider: 2,
    priorKnowledgeSlider: 1,
    applicationBarometer: 4,
    slotsLeft: 5,
    isNew: true,
    isFeatured: true,
    isUrgent: false,
    category: 'Food & Beverage',
    categoryIcon: '☕',
    district: 'District 4 — South',
    districtNum: 4,
    postedDate: '2026-05-21',
    totalHired: '5–10',
    description: 'Join our growing team at Brew & Bean Café! We\'re looking for energetic, customer-focused individuals to join our BGC branch.',
    jobDescription: 'Taking customer orders and processing payments accurately. Preparing coffee drinks and food items according to our standard recipes. Maintaining cleanliness and orderliness of the café area. Assisting in stock replenishment and inventory. Providing friendly and efficient customer service. Following food safety and hygiene standards. Participating in team briefings and trainings.',
    workStartDate: 'Immediately (negotiable)',
    employmentPeriod: 'Regular Part-time (ongoing)',
    holidays: 'Based on shift schedule. At least 2 days off per week.',
    requirements: 'Age 18–30 preferred (age input is optional). No experience required — we will train you! Must be able to communicate in Filipino and basic English. Physically fit for standing work. High school graduate or above.',
    benefits: 'Transportation allowance ₱100–₱150/day. Meal allowance (free drinks during shift). Performance bonus every 6 months. Uniform provided. SSS/PhilHealth/Pag-IBIG for qualified regular part-timers. Employee discount on all menu items.',
    happyBonus: 'Earn up to ₱5,000 Happy Bonus after 3 months of continuous employment!',
    recommendedPoints: [
      'Perfect for students — shift scheduling is very flexible!',
      'Learn barista skills — a valuable life skill you can take anywhere',
      'BGC is a great place to work — modern, safe, and convenient',
      'Fun and young team — staff average age is 20s',
      'Free coffee during every shift!',
    ],
    applicationDest: 'Brew & Bean Café — BGC Branch, 5th Ave corner 26th St, BGC, Taguig',
    howToApply: 'Apply online via this posting and we will contact you within 24 hours. Walk-in applications accepted Mon–Fri 10:00–16:00. Please bring 1 valid ID and 2 copies of your resume.',
    companyInfo: {
      name: 'Brew & Bean Coffee Co., Inc.',
      businessDetails: 'Chain coffee shop operating 15 branches across Metro Manila. Specializing in specialty coffee, pastries, and light meals. Established 2018.',
      url: 'www.brewandbean.ph',
    },
    photoPlaceholder: '☕',
  },
  {
    id: 'j002',
    title: '【Karaoke Staff / Reception / Hostess】Jankara-style Entertainment — Hair & Nails FREELY Styled! No Resume Needed',
    company: 'Sing Star KTV — Cubao Branch',
    employmentType: '[ア・パ] [社員あり]',
    jobType: ['Hall Staff / Service', 'Reception / Front Desk', 'Cashier'],
    salary: { type: 'Hourly', min: 90, max: 130, note: '+ Nightly allowance ₱50 for shifts past 10PM' },
    schedule: ['Shift Consultation', '2/3× a week OK', 'Week 4 OK', '~6 hrs/day', 'No Experience OK', 'Students OK', 'Housewife OK'],
    scheduleNote: '[ア・パ] 12:00–06:00 (shift negotiable, come in as few as 2 days/week!)',
    location: 'Araneta Center, Cubao, Quezon City / Near: Araneta Center LRT-2 & MRT-3',
    nearestStation: ['Araneta Center–Cubao LRT-2 (3 min walk)', 'Araneta Center–Cubao MRT-3 (5 min walk)'],
    features: ['No Experience OK', 'Students OK', 'No Resume Needed', 'Hair & Style Freedom', 'Tattoos OK', 'Night Shift OK', 'Daily Pay Available', 'Housewife / Househusband OK', 'Middle-Aged Welcome', 'Senior Welcome'],
    ageGroupSlider: 3,
    genderRatioSlider: 4,
    workStyleSlider: 2,
    workplaceVibeSlider: 5,
    workTypeSlider: 3,
    customerInteractionSlider: 5,
    externalInteractionSlider: 3,
    priorKnowledgeSlider: 1,
    applicationBarometer: 5,
    slotsLeft: 3,
    isNew: false,
    isFeatured: true,
    isUrgent: true,
    category: 'Entertainment',
    categoryIcon: '🎤',
    district: 'District 2 — Inner East',
    districtNum: 2,
    postedDate: '2026-05-19',
    totalHired: '3–5',
    description: 'Lively KTV entertainment spot looking for outgoing staff who love to interact with customers!',
    jobDescription: 'Welcoming and seating guests in their private KTV rooms. Taking food and beverage orders and delivering promptly. Managing room timers and assisting with karaoke equipment. Processing payments at the front desk. Keeping common areas clean and tidy. Responding to guest requests with a smile.',
    workStartDate: 'Immediately',
    employmentPeriod: 'Regular Part-time, Seasonal, or Short-term available',
    holidays: 'Shift-based. You choose which days you work — minimum 2 days/week.',
    requirements: 'Age 18 and above. No experience or resume required! You just need a positive attitude. Must be able to work at least 2 days per week. Able to follow instructions from senior staff. Willing to work evenings and weekends.',
    benefits: 'Daily pay option available. Nightly allowance (₱50 per shift past 10PM). Uniform provided (with freedom to customize hairstyle and accessories). Staff meal provided during shift. Performance incentives for top staff monthly.',
    happyBonus: 'Happy Bonus ₱3,000 after 60 days of employment!',
    recommendedPoints: [
      'No resume needed — just show up and apply!',
      'Express yourself! Hair color, nails, accessories all welcome',
      'Late night shifts available — great for students with daytime classes',
      'Fast-paced and fun environment — meet new people every day',
      'Path to full-time employment for outstanding performers',
    ],
    applicationDest: 'Sing Star KTV — Cubao Branch, Araneta Center, Quezon City',
    howToApply: 'Walk-in anytime during operating hours (12PM–6AM). Just bring any valid ID. No appointment needed! Online applications also accepted.',
    companyInfo: {
      name: 'Sing Star Entertainment Corp.',
      businessDetails: 'Premium KTV entertainment chain with 8 branches in Metro Manila. Known for high-quality rooms and top-notch service.',
    },
    photoPlaceholder: '🎤',
  },
  {
    id: 'j003',
    title: '【Data Entry / Administrative Support】 Office-Based WFH Option — Fresh Graduates Welcome!',
    company: 'PH Solutions Inc. — Makati Office',
    employmentType: '[ア・パ]',
    jobType: ['Data Entry / Encoding', 'Administrative Support', 'Document Processing'],
    salary: { type: 'Hourly', min: 85, max: 105, note: 'Monthly option: ₱14,000–₱18,000' },
    schedule: ['Weekdays Only', 'Mon–Fri', 'Morning Shift', 'Fixed Schedule', 'WFH Available'],
    scheduleNote: '[ア・パ] 09:00–18:00 (fixed, Mon–Fri)',
    location: 'Ayala Ave, Makati City / Near Ayala MRT-3',
    nearestStation: ['Ayala MRT-3 (5 min walk)', 'Gil Puyat LRT-1 (10 min walk)'],
    features: ['Students OK', 'WFH / Remote Option', 'Fixed Schedule', 'Fresh Graduates OK', 'No Experience OK', 'Training Provided', 'Transportation Allowance'],
    ageGroupSlider: 2,
    genderRatioSlider: 3,
    workStyleSlider: 1,
    workplaceVibeSlider: 1,
    workTypeSlider: 1,
    customerInteractionSlider: 1,
    externalInteractionSlider: 1,
    priorKnowledgeSlider: 2,
    applicationBarometer: 3,
    isNew: true,
    isFeatured: false,
    isUrgent: false,
    category: 'Admin / Office',
    categoryIcon: '📋',
    district: 'District 4 — South',
    districtNum: 4,
    postedDate: '2026-05-20',
    totalHired: '10–15',
    description: 'Looking for detail-oriented individuals for data entry and administrative support roles.',
    jobDescription: 'Encoding and organizing data from physical or digital documents into company systems. Verifying and cross-checking data accuracy. Filing and maintaining digital records. Preparing basic reports in Excel or Google Sheets. Coordinating with other departments for document needs. Supporting the accounting team with basic bookkeeping tasks.',
    workStartDate: 'June 1, 2026 or immediate',
    employmentPeriod: 'Regular Part-time (Mon–Fri only)',
    holidays: 'All Philippine regular holidays off. Fixed 2-day weekend (Sat–Sun).',
    requirements: 'At least senior high graduate or college level. Computer literate — proficient in MS Office (Excel, Word). Typing speed of at least 40 WPM preferred. Good attention to detail. Fluent in written English. Fresh graduates are very welcome.',
    benefits: 'Transportation allowance ₱80–₱120/day. Internet allowance for WFH days. Government-mandated benefits (SSS, PhilHealth, Pag-IBIG). Performance review every 6 months. Option to become regular employee.',
    recommendedPoints: [
      'Perfect for students taking online classes — WFH option means flexibility',
      'Clean, professional office environment in Makati CBD',
      'Build your resume with a reputable company',
      'Learn corporate office skills that will help in any career',
    ],
    applicationDest: 'PH Solutions Inc., 20/F Tower One, Ayala Avenue, Makati City',
    howToApply: 'Apply online. HR will contact shortlisted applicants within 2 business days for a video interview.',
    companyInfo: {
      name: 'PH Solutions Inc.',
      businessDetails: 'Business process outsourcing and professional services company. 200+ employees. Established 2010.',
    },
    photoPlaceholder: '📋',
  },
  {
    id: 'j004',
    title: '【Math / Science Tutor】 After-School Tutoring Center — Earn While You Study!',
    company: 'BrainBoost Learning Center — Ortigas',
    employmentType: '[ア・パ]',
    jobType: ['Tutor / Instructor', 'Academic Coach'],
    salary: { type: 'Hourly', min: 120, max: 180, note: 'Based on subject and student level' },
    schedule: ['Weekday Afternoons', 'Weekends', 'Flexible', '2–4 hrs/session'],
    scheduleNote: '[ア・パ] Afternoon & weekend shifts available — choose your own schedule!',
    location: 'Ortigas Center, Pasig City / ADB Ave',
    nearestStation: ['Ortigas MRT-3 (8 min walk)', 'Shaw Blvd MRT-3 (10 min walk)'],
    features: ['College Students OK', 'Flexible Schedule', 'Prior Knowledge Required', 'Weekends OK', 'Part-time Friendly'],
    ageGroupSlider: 1,
    genderRatioSlider: 3,
    workStyleSlider: 1,
    workplaceVibeSlider: 2,
    workTypeSlider: 1,
    customerInteractionSlider: 4,
    externalInteractionSlider: 1,
    priorKnowledgeSlider: 4,
    applicationBarometer: 2,
    isNew: false,
    isFeatured: false,
    isUrgent: false,
    category: 'Education',
    categoryIcon: '📐',
    district: 'District 2 — Inner East',
    districtNum: 2,
    postedDate: '2026-05-18',
    totalHired: '5–8',
    description: 'Seeking passionate college students or graduates to tutor Grade 4–12 students in Math, Science, and English.',
    jobDescription: 'One-on-one and small group tutoring sessions (max 5 students). Preparing lesson plans and teaching materials. Assessing student progress and reporting to parents. Following the center\'s curriculum while adapting to individual student needs. Attending brief weekly staff meeting (30 min). Maintaining session records and attendance logs.',
    workStartDate: 'June 2026 (school year start)',
    employmentPeriod: 'School Year (June–March), with summer option',
    holidays: 'School holidays off. Christmas break, Holy Week off.',
    requirements: 'Currently enrolled in or graduate of Education, Engineering, Math, Science, or related course. Strong command of subject matter. Patient, clear communicator. Experience in tutoring is a plus but not required. Must pass basic subject evaluation.',
    benefits: 'Competitive hourly rate (higher for advanced subjects). Transportation allowance. Free access to center\'s teaching resources. Certificate of employment. Potential for advancement to Head Tutor.',
    recommendedPoints: [
      'Earn up to ₱180/hour — one of the best rates for student part-timers',
      'Flexible schedule fits around your own class schedule',
      'Teaching others deepens your own understanding of subjects',
      'Excellent experience to put on your resume for future career',
    ],
    applicationDest: 'BrainBoost Learning Center, Unit 302, ADB Tower, Ortigas Center, Pasig City',
    howToApply: 'Submit your application online. You will be asked to take a 30-minute subject assessment test.',
    companyInfo: {
      name: 'BrainBoost Learning Center, Inc.',
      businessDetails: 'K-12 tutoring and learning center with 6 branches in Metro Manila. 15+ years in education support.',
    },
    photoPlaceholder: '📐',
  },
  {
    id: 'j005',
    title: '【Warehouse / Picker / Packer】 E-Commerce Fulfillment — Daily Pay Available! Earn More on Weekends',
    company: 'SwiftShip Logistics — Parañaque Hub',
    employmentType: '[ア・パ] [短期]',
    jobType: ['Warehouse Staff', 'Picker / Packer', 'Inventory Assistant'],
    salary: { type: 'Daily', min: 580, max: 750, note: '+₱100 weekend bonus per day worked' },
    schedule: ['Weekdays OK', 'Weekends OK', 'Morning Shift', 'Evening Shift', 'Daily Pay'],
    scheduleNote: '[ア・パ] 06:00–22:00 rotating shifts (choose morning or evening)',
    location: 'BNBE, Parañaque City / Near PITX',
    nearestStation: ['PITX Terminal (10 min walk)', 'EDSA Bus Carousel — Tramo (15 min)'],
    features: ['Daily Pay Available', 'No Experience OK', 'Weekends OK', 'Short-term OK', 'Overtime Pay', 'Physical Work', 'Uniform Provided'],
    ageGroupSlider: 3,
    genderRatioSlider: 2,
    workStyleSlider: 2,
    workplaceVibeSlider: 3,
    workTypeSlider: 5,
    customerInteractionSlider: 1,
    externalInteractionSlider: 1,
    priorKnowledgeSlider: 1,
    applicationBarometer: 5,
    slotsLeft: 2,
    isNew: false,
    isFeatured: false,
    isUrgent: true,
    category: 'Logistics',
    categoryIcon: '📦',
    district: 'District 4 — South',
    districtNum: 4,
    postedDate: '2026-05-21',
    totalHired: '20–30',
    description: 'Large e-commerce fulfillment warehouse urgently hiring pickers and packers for peak season!',
    jobDescription: 'Picking items from warehouse shelves based on order slips. Packing products securely for shipping. Scanning barcodes and updating inventory system. Maintaining organized warehouse areas. Loading/unloading delivery trucks (with teamwork). Following safety protocols at all times. Achieving daily picking/packing targets (with support from team leads).',
    workStartDate: 'IMMEDIATELY — start as early as tomorrow!',
    employmentPeriod: 'Short-term available (1 week, 1 month) or regular part-time',
    holidays: 'Regular holidays observed. Extra pay for holiday work.',
    requirements: 'Age 18–45. Physically fit — this is a standing and walking job. No experience needed — training provided on day 1. Must be able to lift 10–15kg items. Punctual and reliable.',
    benefits: 'Daily pay option (cash out same day or next day). Weekend bonus ₱100/day extra. Overtime pay 125% on top of daily rate. Uniform and safety shoes provided. Accident insurance. Performance incentives monthly.',
    happyBonus: 'Complete 30 days → receive ₱2,000 completion bonus!',
    recommendedPoints: [
      'Daily pay — ideal if you need money right now',
      'No experience needed — just bring your ID and start working',
      'Peak season means lots of overtime opportunities to earn more',
      'Close to PITX — easy to commute from south areas',
    ],
    applicationDest: 'SwiftShip Logistics — Parañaque Hub, BNBE Zone, Parañaque City',
    howToApply: 'Walk-in applicants welcome anytime Mon–Sat 7AM–5PM. Bring any valid ID. Processing takes 30 minutes and you can start the same day or next day.',
    companyInfo: {
      name: 'SwiftShip Logistics Corp.',
      businessDetails: 'Leading e-commerce logistics partner with 5 fulfillment centers in Metro Manila and Cavite. Handles 50,000+ orders daily.',
    },
    photoPlaceholder: '📦',
  },
  {
    id: 'j006',
    title: '【Customer Service Representative】 BPO Night Shift — High Pay + Night Differential',
    company: 'GlobalConnect BPO — Eastwood City',
    employmentType: '[パ] [社員登用あり]',
    jobType: ['Customer Service Rep', 'Call Center Agent', 'Chat Support'],
    salary: { type: 'Monthly', min: 18000, max: 26000, note: '+25% night differential + performance bonus' },
    schedule: ['Night Shift', 'Graveyard', 'Fixed Days Off', 'US/AU Accounts'],
    scheduleNote: '[パ] 22:00–07:00 or 00:00–09:00 (rotation within night shift)',
    location: 'Eastwood City, Libis, Quezon City',
    nearestStation: ['Araneta Center–Cubao LRT-2 (shuttle 10 min)', 'Katipunan LRT-2 (shuttle 15 min)'],
    features: ['Night Differential', 'High Pay', 'Path to Regular', 'HMO Provided', 'Government Benefits', 'Paid Training', 'Weekly Pay'],
    ageGroupSlider: 2,
    genderRatioSlider: 3,
    workStyleSlider: 1,
    workplaceVibeSlider: 2,
    workTypeSlider: 1,
    customerInteractionSlider: 5,
    externalInteractionSlider: 1,
    priorKnowledgeSlider: 3,
    applicationBarometer: 3,
    isNew: true,
    isFeatured: true,
    isUrgent: false,
    category: 'Customer Service',
    categoryIcon: '🎧',
    district: 'District 2 — Inner East',
    districtNum: 2,
    postedDate: '2026-05-20',
    totalHired: '15–25',
    description: 'Growing BPO company seeking customer service agents for US and AU accounts. Competitive pay with night differential!',
    jobDescription: 'Handling inbound and outbound calls from US/AU customers. Resolving billing, technical, and account-related inquiries. Documenting call notes accurately in CRM system. Meeting daily metrics (CSAT, AHT, FCR). Escalating complex issues to team leads. Participating in weekly team huddles and performance reviews.',
    workStartDate: 'June 2, 2026 (training starts)',
    employmentPeriod: 'Regular part-time with path to full-time in 3 months',
    holidays: 'Philippine holidays observed. Premium pay for holiday work.',
    requirements: 'At least high school graduate (senior high preferred). Excellent English communication skills (spoken and written). Basic computer proficiency. Willing to work night shift. Previous BPO experience is a plus but not required. Must pass mock call assessment.',
    benefits: 'Night differential 25% of base pay. HMO coverage from Day 1 (up to ₱100,000). SSS, PhilHealth, Pag-IBIG. Performance bonus quarterly. Free shuttle service from major train stations. Paid 2-week training. Annual salary review.',
    happyBonus: 'Referral bonus ₱5,000 for every friend you refer who gets hired!',
    recommendedPoints: [
      'One of the highest paying part-time jobs for fresh graduates',
      'Get HMO coverage from Day 1 — medical benefits included',
      'International exposure — handle US and AU customer accounts',
      'Free shuttle from LRT-2 stations — no jeepney/tricycle needed',
      'Clear career path — many of our managers started as part-timers',
    ],
    applicationDest: 'GlobalConnect BPO, 12F Citibank Square, Eastwood City, Quezon City',
    howToApply: 'Apply online with resume. HR will contact you for a mock call assessment within 1 business day.',
    companyInfo: {
      name: 'GlobalConnect Business Process Solutions, Inc.',
      businessDetails: 'Mid-sized BPO company established 2012. 1,500+ employees serving US, Australian, and UK clients in telco, fintech, and retail sectors.',
      url: 'www.globalconnect-bpo.com.ph',
    },
    photoPlaceholder: '🎧',
  },
];

export const QUICK_CONDITIONS = [
  { label: 'Short-term', sub: '7,482 postings', icon: 'Zap' },
  { label: 'Within 1 Month', sub: '1,696 postings', icon: 'CalendarDays' },
  { label: 'Within 1 Week', sub: '70 postings', icon: 'Calendar' },
  { label: 'Within 1 Day', sub: '2,771 postings', icon: 'Rocket' },
  { label: 'Daily Pay', sub: '15,547 postings', icon: 'Banknote' },
];

export const CONDITION_FILTERS = [
  { label: 'High School Students OK', icon: '' },
  { label: 'College Students OK', icon: '' },
  { label: 'Housewife/Husband OK', icon: '' },
  { label: 'Happy Bonus', icon: '' },
  { label: 'WFH / Remote OK', icon: '' },
  { label: 'No Interview', icon: '' },
];

export const TRAIN_LINES = [
  {
    id: 'mrt3', name: 'MRT-3', color: '#1565C0', status: 'operational',
    stations: ['North Avenue', 'Quezon Avenue', 'GMA–Kamuning', 'Araneta Center–Cubao', 'Santolan–Annapolis', 'Ortigas', 'Shaw Boulevard', 'Boni', 'Guadalupe', 'Buendia', 'Ayala', 'Magallanes', 'Taft Avenue'],
  },
  {
    id: 'lrt2', name: 'LRT-2', color: '#6A1B9A', status: 'operational',
    stations: ['Antipolo', 'Marikina–Pasig', 'Santolan', 'Katipunan', 'Anonas', 'Araneta Center–Cubao', 'Betty Go-Belmonte', 'Gilmore', 'J. Ruiz', 'V. Mapa', 'Pureza', 'Legarda', 'Recto'],
  },
  {
    id: 'lrt1', name: 'LRT-1', color: '#E65100', status: 'operational',
    stations: ['Fernando Poe Jr. (Roosevelt)', 'Balintawak', 'Monumento', '5th Avenue', 'R. Papa', 'Abad Santos', 'Blumentritt', 'Tayuman', 'Bambang', 'Doroteo Jose', 'Carriedo', 'Central Terminal', 'United Nations', 'Pedro Gil', 'Quirino', 'Vito Cruz', 'Gil Puyat (Buendia)', 'Libertad', 'EDSA', 'Taft Avenue', 'Baclaran', 'Redemptorist–Aseana', 'MIA Road', 'PITX', 'Ninoy Aquino Avenue', 'Dr. Santos', 'Las Piñas', 'Zapote', 'Niog (Cavite)'],
  },
  {
    id: 'mrt7', name: 'MRT-7', color: '#2E7D32', status: 'under-construction',
    stations: ['North Avenue (Common Station)', 'Quezon Memorial Circle', 'University Avenue', 'Tandang Sora', 'Don Antonio', 'Batasan', 'Manggahan', 'Doña Carmen', 'Regalado Avenue', 'Mindanao Avenue', 'Quirino Highway', 'Sacred Heart', 'Tala', 'San Jose del Monte'],
  },
  {
    id: 'subway', name: 'MRT-9 (Subway)', color: '#00838F', status: 'under-construction',
    stations: ['East Valenzuela', 'Quirino Highway', 'Tandang Sora', 'North Avenue (Common Station)', 'Quezon Avenue', 'East Avenue', 'Anonas', 'Camp Aguinaldo', 'Ortigas', 'Shaw Boulevard', 'Kalayaan Avenue', 'Bonifacio Global City', 'Lawton Avenue', 'Senate–DepEd', 'NAIA Terminal 3', 'FTI', 'Bicutan'],
  },
  {
    id: 'nscr', name: 'NSCR', color: '#BF360C', status: 'under-construction',
    stations: ['New Clark City', 'Clark Intl Airport', 'Angeles', 'San Fernando', 'Apalit', 'Calumpit', 'Malolos', 'Guiguinto', 'Balagtas', 'Bocaue', 'Marilao', 'Meycauayan', 'Valenzuela', 'Malabon', 'Caloocan', 'Solis', 'Tutuban', 'Blumentritt', 'España', 'Santa Mesa', 'Paco', 'Buendia', 'EDSA (Makati)', 'Senate–DepEd', 'FTI', 'Bicutan', 'Sucat', 'Alabang', 'Muntinlupa', 'San Pedro', 'Biñan', 'Santa Rosa', 'Cabuyao', 'Mamatid', 'Banlic', 'Calamba'],
  },
];

export const BUS_ROUTES = [
  {
    id: 'edsa-carousel', name: 'EDSA Bus Carousel', color: '#1B5E20', type: 'bus',
    stops: ['Monumento', 'Balintawak', 'Roosevelt (FPJ)', 'North Avenue', 'Quezon Avenue', 'Nepa Q-Mart', 'Main Avenue', 'Santolan–Annapolis', 'Ortigas', 'Guadalupe', 'Buendia', 'Ayala', 'Magallanes', 'Tramo', 'Taft Avenue', 'Roxas Blvd', 'SM Mall of Asia', 'DFA', 'Ayala Malls Bay', 'PITX'],
  },
  {
    id: 'bgc-east', name: 'BGC Bus — East Express', color: '#0D47A1', type: 'bus',
    stops: ['Ayala (EDSA)', 'Market! Market!'],
  },
  {
    id: 'bgc-north', name: 'BGC Bus — North Route', color: '#0D47A1', type: 'bus',
    stops: ['Ayala (EDSA)', 'HSBC', 'BGC Turf', 'Avida 34th', 'Uptown Mall', 'Globe Tower', 'BGC Arts Center'],
  },
  {
    id: 'makati-ayala', name: 'Makati Ayala Bus', color: '#4A148C', type: 'bus',
    stops: ['One Ayala Terminal', 'Alabang', 'Bicutan', 'Biñan', 'Pacita', 'Sucat', 'FTI', 'Sta. Rosa', 'Tagaytay', 'Dasmariñas', 'Cavite', 'Laguna', 'Rizal', 'Batangas'],
  },
  {
    id: 'pitx', name: 'PITX Terminal', color: '#880E4F', type: 'terminal',
    stops: ['City buses', 'Provincial buses', 'P2P', 'UV Express', 'Baguio', 'Batangas', 'Naga', 'Lucena', 'Cavite', 'Laguna', 'Bicol', 'NAIA Terminals', 'BGC', 'Makati', 'Sucat'],
  },
];

export const P2P_ROUTES = [
  { origin: 'Trinoma', destinations: ['Makati (Greenbelt/Glorietta)', 'Ortigas (Robinsons Galleria)', 'BGC (Market! Market!)'] },
  { origin: 'Alabang', destinations: ['Makati (Greenbelt/Glorietta)', 'Ortigas (Robinsons Galleria)', 'BGC (Market! Market!)'] },
  { origin: 'SM North EDSA', destinations: ['Makati (Circuit/Landmark)', 'BGC (Market! Market!)', 'Ortigas (Robinsons Galleria)'] },
  { origin: 'PITX', destinations: ['NAIA Terminals', 'Makati (Circuit/Landmark)', 'BGC (Market! Market!)', 'Sucat', 'Batangas'] },
];
